name: 构建

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
 
jobs:
  builder_matrix:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x64]
        os: [ubuntu-20.04, windows-latest, macos-13]
        exclude:
          - os: ubuntu-20.04
            arch: x86
          - os: macos-13
            arch: x86
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.8.10'
          architecture: ${{ matrix.arch }}
      - name: Setup uv
        uses: astral-sh/setup-uv@v4
      - name: Run Windows build
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          uv venv
          .venv\Scripts\activate
          uv pip install -r requirements.txt
          uv pip install pyinstaller
          pyinstaller GUI.py `
            -w `
            -i ./icon.ico

      - name: Run Linux build
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -r  requirements.txt
          uv pip install pyinstaller
          pyinstaller GUI.py \
            -w \
            -i ./icon.ico

      - name: Run macOS build
        if: ${{ matrix.os == 'macos-13' }}
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -r  requirements.txt
          uv pip install pyinstaller
          pyinstaller GUI.py \
            -w \
            -i ./icon.ico

      - name: Upload
        uses: actions/upload-artifact@v4.4.2
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: ./dist/ClassWidgets
      - name: Upload macOS Bundle
        if: ${{ matrix.os == 'macos-13' }}
        uses: actions/upload-artifact@v4.4.2
        with:
          name: macos-13-bundle
          path: ./dist/ClassWidgets.app
